const cartTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  ADD_QTY_ITEM: "ADD_QTY_ITEM",
  MINUS_QTY_ITEM: "MINUS_QTY_ITEM",
  DEL_QTY_ITEM: "DEL_QTY_ITEM",
  ADD_DELIVERY: "ADD_DELIVERY",
  ADD_DELIVERY_SUCCESS: "ADD_DELIVERY_SUCCESS",
  SEND_CART_TO_DATA: "SEND_CART_TO_DATA",
  CLEAR_CART: "CLEAR_CART",
};

export default cartTypes;
